/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoverageRouteImport } from './routes/coverage'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ReviewQueueRouteImport } from './routes/review-queue'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibraryGuideIdRouteImport } from './routes/library.$guideId'
import { Route as LibraryNewRouteImport } from './routes/library.new'
import { Route as LibraryEditGuideIdRouteImport } from './routes/library.edit.$guideId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverageRoute = CoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewQueueRoute = ReviewQueueRouteImport.update({
  id: '/review-queue',
  path: '/review-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryGuideIdRoute = LibraryGuideIdRouteImport.update({
  id: '/$guideId',
  path: '/$guideId',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryNewRoute = LibraryNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryEditGuideIdRoute = LibraryEditGuideIdRouteImport.update({
  id: '/edit/$guideId',
  path: '/edit/$guideId',
  getParentRoute: () => LibraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coverage': typeof CoverageRoute
  '/delivery': typeof DeliveryRoute
  '/library': typeof LibraryRouteWithChildren
  '/review-queue': typeof ReviewQueueRoute
  '/sources': typeof SourcesRoute
  '/library/$guideId': typeof LibraryGuideIdRoute
  '/library/new': typeof LibraryNewRoute
  '/library/': typeof LibraryIndexRoute
  '/library/edit/$guideId': typeof LibraryEditGuideIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coverage': typeof CoverageRoute
  '/delivery': typeof DeliveryRoute
  '/review-queue': typeof ReviewQueueRoute
  '/sources': typeof SourcesRoute
  '/library/$guideId': typeof LibraryGuideIdRoute
  '/library/new': typeof LibraryNewRoute
  '/library': typeof LibraryIndexRoute
  '/library/edit/$guideId': typeof LibraryEditGuideIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coverage': typeof CoverageRoute
  '/delivery': typeof DeliveryRoute
  '/library': typeof LibraryRouteWithChildren
  '/review-queue': typeof ReviewQueueRoute
  '/sources': typeof SourcesRoute
  '/library/$guideId': typeof LibraryGuideIdRoute
  '/library/new': typeof LibraryNewRoute
  '/library/': typeof LibraryIndexRoute
  '/library/edit/$guideId': typeof LibraryEditGuideIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coverage'
    | '/delivery'
    | '/library'
    | '/review-queue'
    | '/sources'
    | '/library/$guideId'
    | '/library/new'
    | '/library/'
    | '/library/edit/$guideId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coverage'
    | '/delivery'
    | '/review-queue'
    | '/sources'
    | '/library/$guideId'
    | '/library/new'
    | '/library'
    | '/library/edit/$guideId'
  id:
    | '__root__'
    | '/'
    | '/coverage'
    | '/delivery'
    | '/library'
    | '/review-queue'
    | '/sources'
    | '/library/$guideId'
    | '/library/new'
    | '/library/'
    | '/library/edit/$guideId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoverageRoute: typeof CoverageRoute
  DeliveryRoute: typeof DeliveryRoute
  LibraryRoute: typeof LibraryRouteWithChildren
  ReviewQueueRoute: typeof ReviewQueueRoute
  SourcesRoute: typeof SourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coverage': {
      id: '/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof CoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-queue': {
      id: '/review-queue'
      path: '/review-queue'
      fullPath: '/review-queue'
      preLoaderRoute: typeof ReviewQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/$guideId': {
      id: '/library/$guideId'
      path: '/$guideId'
      fullPath: '/library/$guideId'
      preLoaderRoute: typeof LibraryGuideIdRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/new': {
      id: '/library/new'
      path: '/new'
      fullPath: '/library/new'
      preLoaderRoute: typeof LibraryNewRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/edit/$guideId': {
      id: '/library/edit/$guideId'
      path: '/edit/$guideId'
      fullPath: '/library/edit/$guideId'
      preLoaderRoute: typeof LibraryEditGuideIdRouteImport
      parentRoute: typeof LibraryRoute
    }
  }
}

interface LibraryRouteChildren {
  LibraryGuideIdRoute: typeof LibraryGuideIdRoute
  LibraryNewRoute: typeof LibraryNewRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  LibraryEditGuideIdRoute: typeof LibraryEditGuideIdRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryGuideIdRoute: LibraryGuideIdRoute,
  LibraryNewRoute: LibraryNewRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  LibraryEditGuideIdRoute: LibraryEditGuideIdRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoverageRoute: CoverageRoute,
  DeliveryRoute: DeliveryRoute,
  LibraryRoute: LibraryRouteWithChildren,
  ReviewQueueRoute: ReviewQueueRoute,
  SourcesRoute: SourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
