/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoverageRouteImport } from './routes/coverage'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ReviewQueueRouteImport } from './routes/review-queue'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as HelpIndexRouteImport } from './routes/help.index'
import { Route as HelpBrowseRouteImport } from './routes/help.browse'
import { Route as HelpSearchRouteImport } from './routes/help.search'
import { Route as IntegrationAuraHelpRouteImport } from './routes/integration.aura-help'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibraryGuideIdRouteImport } from './routes/library.$guideId'
import { Route as LibraryNewRouteImport } from './routes/library.new'
import { Route as HelpGuideGuideIdRouteImport } from './routes/help.guide.$guideId'
import { Route as LibraryEditGuideIdRouteImport } from './routes/library.edit.$guideId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverageRoute = CoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewQueueRoute = ReviewQueueRouteImport.update({
  id: '/review-queue',
  path: '/review-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HelpRoute,
} as any)
const HelpBrowseRoute = HelpBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => HelpRoute,
} as any)
const HelpSearchRoute = HelpSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => HelpRoute,
} as any)
const IntegrationAuraHelpRoute = IntegrationAuraHelpRouteImport.update({
  id: '/integration/aura-help',
  path: '/integration/aura-help',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryGuideIdRoute = LibraryGuideIdRouteImport.update({
  id: '/$guideId',
  path: '/$guideId',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryNewRoute = LibraryNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LibraryRoute,
} as any)
const HelpGuideGuideIdRoute = HelpGuideGuideIdRouteImport.update({
  id: '/guide/$guideId',
  path: '/guide/$guideId',
  getParentRoute: () => HelpRoute,
} as any)
const LibraryEditGuideIdRoute = LibraryEditGuideIdRouteImport.update({
  id: '/edit/$guideId',
  path: '/edit/$guideId',
  getParentRoute: () => LibraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coverage': typeof CoverageRoute
  '/delivery': typeof DeliveryRoute
  '/help': typeof HelpRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/review-queue': typeof ReviewQueueRoute
  '/sources': typeof SourcesRoute
  '/help/browse': typeof HelpBrowseRoute
  '/help/search': typeof HelpSearchRoute
  '/integration/aura-help': typeof IntegrationAuraHelpRoute
  '/library/$guideId': typeof LibraryGuideIdRoute
  '/library/new': typeof LibraryNewRoute
  '/help/': typeof HelpIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/help/guide/$guideId': typeof HelpGuideGuideIdRoute
  '/library/edit/$guideId': typeof LibraryEditGuideIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coverage': typeof CoverageRoute
  '/delivery': typeof DeliveryRoute
  '/review-queue': typeof ReviewQueueRoute
  '/sources': typeof SourcesRoute
  '/help/browse': typeof HelpBrowseRoute
  '/help/search': typeof HelpSearchRoute
  '/integration/aura-help': typeof IntegrationAuraHelpRoute
  '/library/$guideId': typeof LibraryGuideIdRoute
  '/library/new': typeof LibraryNewRoute
  '/help': typeof HelpIndexRoute
  '/library': typeof LibraryIndexRoute
  '/help/guide/$guideId': typeof HelpGuideGuideIdRoute
  '/library/edit/$guideId': typeof LibraryEditGuideIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coverage': typeof CoverageRoute
  '/delivery': typeof DeliveryRoute
  '/help': typeof HelpRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/review-queue': typeof ReviewQueueRoute
  '/sources': typeof SourcesRoute
  '/help/browse': typeof HelpBrowseRoute
  '/help/search': typeof HelpSearchRoute
  '/integration/aura-help': typeof IntegrationAuraHelpRoute
  '/library/$guideId': typeof LibraryGuideIdRoute
  '/library/new': typeof LibraryNewRoute
  '/help/': typeof HelpIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/help/guide/$guideId': typeof HelpGuideGuideIdRoute
  '/library/edit/$guideId': typeof LibraryEditGuideIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coverage'
    | '/delivery'
    | '/help'
    | '/library'
    | '/review-queue'
    | '/sources'
    | '/help/browse'
    | '/help/search'
    | '/integration/aura-help'
    | '/library/$guideId'
    | '/library/new'
    | '/help/'
    | '/library/'
    | '/help/guide/$guideId'
    | '/library/edit/$guideId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coverage'
    | '/delivery'
    | '/review-queue'
    | '/sources'
    | '/help/browse'
    | '/help/search'
    | '/integration/aura-help'
    | '/library/$guideId'
    | '/library/new'
    | '/help'
    | '/library'
    | '/help/guide/$guideId'
    | '/library/edit/$guideId'
  id:
    | '__root__'
    | '/'
    | '/coverage'
    | '/delivery'
    | '/help'
    | '/library'
    | '/review-queue'
    | '/sources'
    | '/help/browse'
    | '/help/search'
    | '/integration/aura-help'
    | '/library/$guideId'
    | '/library/new'
    | '/help/'
    | '/library/'
    | '/help/guide/$guideId'
    | '/library/edit/$guideId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoverageRoute: typeof CoverageRoute
  DeliveryRoute: typeof DeliveryRoute
  HelpRoute: typeof HelpRouteWithChildren
  LibraryRoute: typeof LibraryRouteWithChildren
  ReviewQueueRoute: typeof ReviewQueueRoute
  SourcesRoute: typeof SourcesRoute
  IntegrationAuraHelpRoute: typeof IntegrationAuraHelpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coverage': {
      id: '/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof CoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-queue': {
      id: '/review-queue'
      path: '/review-queue'
      fullPath: '/review-queue'
      preLoaderRoute: typeof ReviewQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/browse': {
      id: '/help/browse'
      path: '/browse'
      fullPath: '/help/browse'
      preLoaderRoute: typeof HelpBrowseRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/search': {
      id: '/help/search'
      path: '/search'
      fullPath: '/help/search'
      preLoaderRoute: typeof HelpSearchRouteImport
      parentRoute: typeof HelpRoute
    }
    '/integration/aura-help': {
      id: '/integration/aura-help'
      path: '/integration/aura-help'
      fullPath: '/integration/aura-help'
      preLoaderRoute: typeof IntegrationAuraHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/$guideId': {
      id: '/library/$guideId'
      path: '/$guideId'
      fullPath: '/library/$guideId'
      preLoaderRoute: typeof LibraryGuideIdRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/new': {
      id: '/library/new'
      path: '/new'
      fullPath: '/library/new'
      preLoaderRoute: typeof LibraryNewRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/help/guide/$guideId': {
      id: '/help/guide/$guideId'
      path: '/guide/$guideId'
      fullPath: '/help/guide/$guideId'
      preLoaderRoute: typeof HelpGuideGuideIdRouteImport
      parentRoute: typeof HelpRoute
    }
    '/library/edit/$guideId': {
      id: '/library/edit/$guideId'
      path: '/edit/$guideId'
      fullPath: '/library/edit/$guideId'
      preLoaderRoute: typeof LibraryEditGuideIdRouteImport
      parentRoute: typeof LibraryRoute
    }
  }
}

interface HelpRouteChildren {
  HelpBrowseRoute: typeof HelpBrowseRoute
  HelpSearchRoute: typeof HelpSearchRoute
  HelpIndexRoute: typeof HelpIndexRoute
  HelpGuideGuideIdRoute: typeof HelpGuideGuideIdRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpBrowseRoute: HelpBrowseRoute,
  HelpSearchRoute: HelpSearchRoute,
  HelpIndexRoute: HelpIndexRoute,
  HelpGuideGuideIdRoute: HelpGuideGuideIdRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

interface LibraryRouteChildren {
  LibraryGuideIdRoute: typeof LibraryGuideIdRoute
  LibraryNewRoute: typeof LibraryNewRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  LibraryEditGuideIdRoute: typeof LibraryEditGuideIdRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryGuideIdRoute: LibraryGuideIdRoute,
  LibraryNewRoute: LibraryNewRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  LibraryEditGuideIdRoute: LibraryEditGuideIdRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoverageRoute: CoverageRoute,
  DeliveryRoute: DeliveryRoute,
  HelpRoute: HelpRouteWithChildren,
  LibraryRoute: LibraryRouteWithChildren,
  ReviewQueueRoute: ReviewQueueRoute,
  SourcesRoute: SourcesRoute,
  IntegrationAuraHelpRoute: IntegrationAuraHelpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
